language: cpp
compiler:
  - gcc
  - clang
before_install:
  - pushd /tmp && git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git && export PATH=`pwd`/depot_tools:"$PATH" && popd
  - gclient config --unmanaged https://chromium.googlesource.com/crashpad/crashpad
  - gclient sync
script:
  - ninja -C out/Debug
  - ninja -C out/Release
notifications:
  recipients:
    - scottmg@chromium.org
  email:
    on_success: change
    on_failure: always
os:
  - linux
  - osx
